### ISSUE TITLE
Firefox cannot set src attribute 

### ISSUE THREAD

**Issue by altun** [NARKOZ/holder_rails#8]
Example sceneraio:

```slim
/ working code
img data-src="holder.js/60x60"

/ not working/buggy code
= holder_tag '60x60'
```

In not working code part, Firefox produce below code (in here `src` is empty),

```html
<img data-src="holder.js/60x60" src="">
```

**Comment by NARKOZ** [comment]
What version of Firefox are you using? Works for me in FF33 Mac. 

Anyway that seems an issue with holder.js 
Please open the issue at https://github.com/imsky/holder

**Comment by mortenjakobsen** [comment]
I have the same problem in Firefox 44.0.2 on OS X 10.11.2. It works in Google Chrome.

It seems it occurs because the `src` attribute on the image i set.

**Example**
This doesn't work:
```html
<img data-src="holder.js/60x60" src="">
```

This works:
```html
<img data-src="holder.js/60x60">
```

You can argue that this is a holder.js issue - though it's easy fixed, by not setting the `src` attribute.

Any change you could remove this in the `holderjs_tag function`?

**Comment by blimey85** [comment]
Any reason this issue has never been resolved? Seems odd to leave an empty src field within the tag, especially knowing it's causing issues. I was testing first with Firefox since I use Firebug a lot, and thought I wasn't getting the gem to work correctly, and then came across this, tried in Safari, and it works fine, just not in Firefox.

**Comment by mibamur** [comment]
Hello!
solution
```js
  $('.holdertag').removeAttr('src');
  Holder.run();
```

**Comment by mibamur** [comment]
https://github.com/imsky/holder/issues/91
